services:
  - type: web
    name: groww-pulse-api
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker --timeout 120 --log-level debug src.phase6_api.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: MCP_SERVER_URL
        sync: false
      - key: GOOGLE_MASTER_DOC_ID
        sync: false
      - key: PULSE_EMAIL_RECIPIENT
        sync: false
